### ISSUE TITLE
Issue on the README documentation

### ISSUE THREAD

**Issue by josisusan** [tpitale/swagger_yard#24]
Hi,
Thanks for your wonderful gem. I have faced some problems while following your README guideline . When I try accessing page `http://<- root_url ->/swagger/docs`, it shows me
```   No route matches [GET] "/swagger/docs" ```
But when I do ` http://<- root_url ->/swagger/doc `, it works fine.
Is it just me?

**Comment by tpitale** [comment]
It might be a typo. I'll try to take a look.

**Comment by tpitale** [comment]
You're correct, both here: https://github.com/tpitale/swagger_yard/blob/master/app/controllers/swagger_yard/swagger_controller.rb#L18 and in the routes use '/doc'. I'll update the README.

**Comment by tpitale** [comment]
Updated: 01e095a1fcde4ea38a15bc9fceb18a3c93b0d8c9

**Comment by josisusan** [comment]
Thanks :smile:
